version: "3.9"

services:
  budget-api:
    build:
      dockerfile: local.Dockerfile
      target: budget-api-development
    depends_on:
      - postgres
    environment:
      # AWS_ACCESS_KEY_ID: ${NPS_AWS_ACCESS_KEY}
      # AWS_REGION: us-west-2
      # AWS_SECRET_ACCESS_KEY: ${NPS_AWS_SECRET_KEY}
      # ENV: dev
      MAVEN_CONFIG: /root/.m2
      SPRING_PROFILES_ACTIVE: local
      SERVER_PORT: 80
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: examplepassword
      # VIRTUAL_HOST: budget.bucks.test
      # VIRTUAL_PORT: 80
      # VIRTUAL_PROTO: http
    expose:
      - 80
    ports:
      - 5001:5001 # dt_socket for Java Debug Attach
      - 8080:80
    tty: true
    volumes:
      - ./:/usr/src/app
      - ${HOME}/.m2/repository:/root/.m2/repository

  nginx-proxy:
    image: jwilder/nginx-proxy:1.0
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      # - ./ssl:/etc/nginx/certs

  liquibase:
    depends_on:
      - postgres
    image: liquibase/liquibase:4.18
    entrypoint: ["liquibase", "--defaultsFile=/liquibase/changelog/liquibase.properties"]
    command: ["update"]
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
      # - ./liquibase:/liquibase/changelog

  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
