spring:
  application:
    name: budget-app-api
  http:
    encoding:
      charset: UTF-8 # Added to the "Content-Type" header if not set explicitly
      enabled: true
      force-response: true # Force the encoding to the configured charset on HTTP responses
  jackson:
    mapper:
      accept-case-insensitive-enums: true
      # Not sure why following does not work, but
      # using SampleRequest "format" annotation and it works
      # ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
  liquibase:
    enabled: false # disable spring liquibase for now and use liquibase container

database:
  connection:
    pool:
      size: 120

logging:
  level:
    root: INFO
  com:
    rstachelczyk: INFO

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    threaddump:
      enabled: true
    heapdump:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,loggers,metrics,threaddump,heapdump"
  health:
    env:
      enabled: true
    show-details: always
  info:
    env:
      enabled: true

info:
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    version: '@project.version@'

token.expiration: 3600000

token.secret.key: dce7fe86f4cb0bf3b04cdf46fb456fe79baf5919cebf49456b37fa222041d70f
