name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  SPRING_PROFILES_ACTIVE: local
  CACHE_NAME: cache-maven-deps

jobs:
#  lint-dockerfile:
#    name: Lint local.Dockerfile
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: hadolint/hadolint-action@v2.0.0

  lint-java:
    name: Lint Java
    runs-on: ubuntu-latest
#    needs: lint-dockerfile
    steps:
      - name: Set up JDK 17
        uses: actions/setup/java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-default
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build and lint
        run: mvn -B -Dmaven.test.skip=true checkstyle:checkstyle

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint-java
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-default
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build and test with Maven
        run: mvn --batch-mode --update-snapshots test -DexcludedGroups="integration"
